### ISSUE TITLE
unable to find an inherited method for function ‘writeMM’ for signature ‘"data.frame"’

### ISSUE THREAD

**Issue by minghlijiyi** [GregorySchwartz/tooManyCellsR#3]
Hi, 
I follow the instruction command line to installed too-many-cells in Docker.
When I run the data in R, the error is" unable to find an inherited method for function ‘writeMM’ for signature ‘"data.frame"’ ". Please see the below codes. Thanks a lot for the help in advance, I can't wait to use such a cool algorithm.

<img width="719" alt="Screen Shot 2020-09-01 at 16 55 22" src="https://user-images.githubusercontent.com/51270057/91913157-f182b480-ec82-11ea-87d3-f767eca0ab04.png">

**Comment by GregorySchwartz** [comment]
Is `mat2` a data frame or a matrix?

**Comment by minghlijiyi** [comment]
> Is `mat2` a data frame or a matrix?

It is a data frame, I also tried converting to the matrix, I get the same error.

<img width="698" alt="Screen Shot 2020-09-02 at 11 38 04" src="https://user-images.githubusercontent.com/51270057/92004882-c6df3d00-ed10-11ea-8a9b-f371bd1180d7.png">

**Comment by GregorySchwartz** [comment]
Did you try:

`mat2 = Matrix::Matrix(as.matrix(mat2), sparse = TRUE)`

**Comment by minghlijiyi** [comment]
I just did, I got the error of "command not found", it is the same with other guys. 
<img width="740" alt="Screen Shot 2020-09-02 at 12 00 22" src="https://user-images.githubusercontent.com/51270057/92007472-02c7d180-ed14-11ea-933e-4e8047885999.png">

**Comment by GregorySchwartz** [comment]
That's because you first need to install `too-many-cells`.

**Comment by minghlijiyi** [comment]
I already installed too-many-cells following the tutorial before I run the code in R. Does it mean I install fail?

**Comment by GregorySchwartz** [comment]
Is it in your path? What's the output of `which too-many-cells`?

**Comment by minghlijiyi** [comment]
Thank you for your reply! I set the docker path like this, it still has the error.
> tooManyCells(mat2, args = c("make-tree"),docker="gregoryschwartz/too-many-cells:0.2.2.0")
"Loading matrix [..........................................................]   0%too-many-cells: ./Data/Vector/Generic.hs:245 ((!)): i**ndex out of bounds (0,0)**
CallStack (from HasCallStack):
  **error, called at** ./Data/Vector/Internal/Check.hs:87:5 in vector-0.12.0.1-GGZqQZyzchy8YFPCF67wxL:Data.Vector.Internal.Check
Error in read.table(file = file, header = header, sep = sep, quote = quote,  : 
  no lines available in input
In addition: Warning messages:
1: **In dir.create(output, recursive = TRUE) : 'out' already exists**
2: **In system2("docker", args = c(dockerArgs, args, autoArgs), stdout = TRUE) :**
  running command ''docker' run -i --rm -v "/var/folders/v8/dp65mt310c9fjqc33y6jlp4h0000gn/T//RtmpJlfzUX:/var/folders/v8/dp65mt310c9fjqc33y6jlp4h0000gn/T//RtmpJlfzUX -v /Users/minglijiyi/Data0803/out:/Users/minglijiyi/Data0803/out gregoryschwartz/too-many-cells:0.2.2.0 make-tree --matrix-path /var/folders/v8/dp65mt310c9fjqc33y6jlp4h0000gn/T//RtmpJlfzUX --output /Users/minglijiyi/Data0803/out' **had status 1**

**Comment by GregorySchwartz** [comment]
Looks like you are using an older version of `too-many-cells` which automatically filters based on scRNA-seq data. You have transformed data (negative values), so the cells are filtered out. You should provide the `-F` and `--normalization NoneNorm` arguments to avoid this issue.

**Comment by minghlijiyi** [comment]
I install the latest version now, the error is incompatible matrix sizes, could you tell me where could I download an example data for TooManyCellsR?  I only find the example data for too-many-cells. Thank you!
> mat2 <- Matrix::Matrix(as.matrix(mat), sparse = TRUE)
> tooManyCells(mat2, args = c("make-tree"), docker="gregoryschwartz/too-many-cells:2.0.0.0")
too-many-cells: matMat : **incompatible matrix sizes**((1495155,3),(1,1))
CallStack (from HasCallStack):
  error, called at src/Data/Sparse/SpMatrix.hs:793:22 in sparse-linear-algebra-0.3.2-LJ5QWDyWqk8g1L9MLmVBX:Data.Sparse.SpMatrix
Registered S3 method overwritten by 'imager':
  method      from
  plot.imlist     
Error in wrap.url(file, load.image.internal) : File not found

**Comment by GregorySchwartz** [comment]
https://gregoryschwartz.github.io/too-many-cells/workshop/workshop.html

**Comment by minghlijiyi** [comment]
Thank you so much for helping!

**Comment by GregorySchwartz** [comment]
Let me know if it works out.

**Comment by minghlijiyi** [comment]
I run the small toy example in the R package, the error is **" Unsupported file format. Please convert to jpeg/png/bmp or install image magick"**, it gives me the output files except except "projection.pdf", but the clumpiness is empty.
<img width="661" alt="1" src="https://user-images.githubusercontent.com/51270057/92255880-edcc7900-eea0-11ea-8253-18f618d4ecb9.png">

**Comment by minghlijiyi** [comment]
I modify my data to the same structure as the example, but the error is still "incompatible matrix size".
<img width="765" alt="Screen Shot 2020-09-04 at 12 10 00" src="https://user-images.githubusercontent.com/51270057/92262452-23756000-eea9-11ea-8690-2af5377cf122.png">

**Comment by GregorySchwartz** [comment]
What if you tried an earlier docker image for the unsupported file format error? Like version `0.2.2.0`? There's been a change in the way I make the docker image so I wonder if I'm missing a dependency.

**Comment by GregorySchwartz** [comment]
Wait, did you say that there was an output tree file? Then you should install image magick as R says.

**Comment by GregorySchwartz** [comment]
For your remaining issue, can I see an example of the format of the matrix?

**Comment by minghlijiyi** [comment]
Hi Gregory, Sorry for the delayed response. 
I use the command line to run it in the docker well, so I will close this issue.
Thank you so much for your help!
