### ISSUE TITLE
R and Docker on Windows

### ISSUE THREAD

**Issue by mcclo** [GregorySchwartz/tooManyCellsR#4]
Hi! Thank you for developing the TooManyCells package! Your paper was an exciting read. I'm somewhat new to coding and mainly use R. I'm having a similar problem to the previous issues where I download Docker and successfully pull the docker image for too-many-cells:2.0.0.0 and then run directly indicating either my user folder or my specific R library Path:

*Using Windows Git CMD to run the below.
I've also tried the below with "C:/Users/mcclo:/mcclo", both run with administrator privileges. 

C:\Users\mcclo>docker run -it --rm -v "C:/Program Files/R/R-4.0.2/library:/library" gregoryschwartz/too-many-cells:2.0.0.0 -h
too-many-cells, Gregory W. Schwartz. Clusters and analyzes single cell data.

Usage: too-many-cells (make-tree | interactive | differential | diversity |
                      paths | classify | peaks | motifs | matrix-output)

Available options:
  -h,--help                Show this help text

Available commands:
  make-tree
  interactive
  differential
  diversity
  paths
  classify
  peaks
  motifs
  matrix-output

**In R:**
The R package also installs successfully but when I go to run the example I get the following:
> res = tooManyCells(mat, labels = labelsDf
+                     , args = c( "make-tree"
+                                 , "--no-filter"
+                                 , "--normalization", "NoneNorm"
+                                 , "--draw-max-node-size", "40"
+                                 , "--draw-max-leaf-node-size", "70"
+                                 , docker = "gregoryschwartz/too-many-cells:2.0.0.0"
+                     )
+ )
**Error in system2("too-many-cells", args = c(args, autoArgs), stdout = TRUE) : 
  '"too-many-cells"' not found
In addition: Warning message:
In dir.create(output, recursive = TRUE) : 'out' already exists**

I believe this is an issue with my installation, specifically in connecting the Path as noted in your instructions "This package requires =too-many-cells= to be installed and in your path! "

I wondered if you could elaborate on how to set up the Path. Is this in R or Docker? The docker image path is a tad confusing to a beginning like me! 

Any help would be greatly appreciated, I think TooManyCells will be perfect for our applications. 

Curtis

**Comment by minghlijiyi** [comment]
You can try to put the "docker" out of  the args
args = c( "make-tree"
                            , "--no-filter"
                            , "--normalization", "NoneNorm"
                            , "--draw-max-node-size", "40"
                            , "--draw-max-leaf-node-size", "70"
                            
                ), docker = "gregoryschwartz/too-many-cells:2.0.0.0"
)

**Comment by mcclo** [comment]
Hi, thank you for noticing that, tried that and getting a path issue as well I believe: 

> res = tooManyCells(mat, labels = labelsDf
+                     , args = c( "make-tree"
+                                 , "--no-filter"
+                                 , "--normalization", "NoneNorm"
+                                 , "--draw-max-node-size", "40"
+                                 , "--draw-max-leaf-node-size", "70")
+                    , docker = "gregoryschwartz/too-many-cells:2.0.0.0"
+ )
Error in wrap.url(file, load.image.internal) : File not found
In addition: Warning messages:
1: In dir.create(output, recursive = TRUE) : 'out' already exists
2: In system2("docker", args = c(dockerArgs, args, autoArgs), stdout = TRUE) :
  running command '"docker" run -i --rm -v C:\Users\mcclo\AppData\Local\Temp\Rtmpo5bu5z:C:\Users\mcclo\AppData\Local\Temp\Rtmpo5bu5z -v C:\Program Files\R\R-4.0.2\out:C:\Program Files\R\R-4.0.2\out gregoryschwartz/too-many-cells:2.0.0.0 make-tree --no-filter --normalization NoneNorm --draw-max-node-size 40 --draw-max-leaf-node-size 70 --matrix-path C:\Users\mcclo\AppData\Local\Temp\Rtmpo5bu5z --output C:\Program Files\R\R-4.0.2\out --labels-file C:\Users\mcclo\AppData\Local\Temp\Rtmpo5bu5z/labels.csv' had status 125

**Comment by minghlijiyi** [comment]
Try to add your data file path in the docker
<img width="887" alt="Screen Shot 2020-09-04 at 17 40 01" src="https://user-images.githubusercontent.com/51270057/92288886-95b36800-eedc-11ea-8922-97e52966eec2.png">

**Comment by mcclo** [comment]
Sorry for my delayed response. I tried a few things but it was easier for me to use the Nix installation and move my analysis over to Ubuntu. Thanks again for the help! I'll close the issue.
